set MATLAB=C:/MATLAB/R2006a
"C:\MATLAB\R2006a\toolbox\rtw\targets\mpc555dk\bin\win32\make.exe" -f serial_test.mk  MPC555_OPTIMIZATION_SWITCH="speed" EXECUTION_PROFILING_NUM_SAMPLES=500 RELATIVE_PATH_TO_ANCHOR=..
